name: Test javascript-node.sh

on: push

jobs:
  test-on-macos-ventura-x86_64:
    runs-on: macos-13
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run a script using zsh
      - name: Run script
        run: |
          echo $HOME
          ./macos/install/javascript-node.sh
          echo "cat ~/.bash_profile"
          cat ~/.bash_profile
          echo "cat ~/.bashrc"
          cat ~/.bashrc
          echo "cat ~/.zshrc"
          cat ~/.zshrc
        shell: zsh {0}
  
  test-on-macos-sonoma-arm64:
    runs-on: macos-14
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run a script using zsh
      - name: Run script
        run: |
          echo $HOME
          ./macos/install/javascript-node.sh
          echo "cat ~/.bash_profile"
          cat ~/.bash_profile
          echo "cat ~/.bashrc"
          cat ~/.bashrc
          echo "cat ~/.zshrc"
          cat ~/.zshrc
        shell: zsh {0}