name: Test javascript-node.sh

on: push

env:
  # Overwrite the default shell to zsh
  SHELL: /bin/zsh

jobs:
  test-on-macos-ventura-x86_64:
    runs-on: macos-13
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      - name: Install Node.js 20.0.0
        run: |
          ./macos/install/javascript-node.sh -v 20.0.0
        shell: zsh {0}
      - name: Install Node.js 20.18.1
        run: |
          ./macos/install/javascript-node.sh -v 20.18.1
        shell: zsh {0}
      - name: Install Node.js 22.12.0
        run: |
          ./macos/install/javascript-node.sh -v 22.12.0
        shell: zsh {0}
      - name: Install Node.js 23.4.0
        run: |
          ./macos/install/javascript-node.sh -v 23.4.0
        shell: zsh {0}
  
  test-on-macos-sonoma-arm64:
    runs-on: macos-14
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      - name: Install Node.js 20.0.0
        run: |
          ./macos/install/javascript-node.sh -v 20.0.0
        shell: zsh {0}
      - name: Install Node.js 20.18.1
        run: |
          ./macos/install/javascript-node.sh -v 20.18.1
        shell: zsh {0}
      - name: Install Node.js 22.12.0
        run: |
          ./macos/install/javascript-node.sh -v 22.12.0
        shell: zsh {0}
      - name: Install Node.js 23.4.0
        run: |
          ./macos/install/javascript-node.sh -v 23.4.0
        shell: zsh {0}