name: Test python.sh

on: push

jobs:
  test-on-macos-ventura-x86_64:
    runs-on: macos-13
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      - name: Install Python 3.9.0
        run: |
          ./macos/install/python.sh -v 3.9.0
        shell: zsh {0}
      - name: Install Python 3.9.21
        run: |
          ./macos/install/python.sh -v 3.9.21
        shell: zsh {0}
      - name: Install Python 3.13.1
        run: |
          ./macos/install/python.sh -v 3.13.1
        shell: zsh {0}
  
  test-on-macos-sonoma-arm64:
    runs-on: macos-14
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      - name: Install Python 3.9.0
        run: |
          brew list --versions
          ./macos/install/python.sh -v 3.9.0
        shell: zsh {0}
      - name: Install Python 3.9.21
        run: |
          ./macos/install/python.sh -v 3.9.21
        shell: zsh {0}
      - name: Install Python 3.13.1
        run: |
          ./macos/install/python.sh -v 3.13.1
        shell: zsh {0}