name: Test python.sh

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

env:
  # Overwrite the default shell to zsh
  SHELL: /bin/zsh

jobs:
  test-on-macos-ventura-x86_64:
    runs-on: macos-13
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      - name: Install Python 3.9.1
        run: |
          ./macos/install/python.sh -v 3.9.1
        shell: zsh {0}
      - name: Install Python 3.9.21
        run: |
          cat ~/.zshrc
          echo $PYENV_ROOT
          echo $PATH
          ./macos/install/python.sh -v 3.9.21
        shell: zsh {0}
      - name: Install Python 3.10.16
        run: |
          ./macos/install/python.sh -v 3.10.16
        shell: zsh {0}
      - name: Install Python 3.11.11
        run: |
          ./macos/install/python.sh -v 3.11.11
        shell: zsh {0}
      - name: Install Python 3.12.8
        run: |
          ./macos/install/python.sh -v 3.12.8
        shell: zsh {0}
      - name: Install Python 3.13.1
        run: |
          ./macos/install/python.sh -v 3.13.1
        shell: zsh {0}
      - name: List all Python versions
        run: |
          source ~/.zshrc
          pyenv versions
        shell: zsh {0}
  
  test-on-macos-sonoma-arm64:
    runs-on: macos-14
    steps:
      # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v4
      # Run the script using zsh
      # 3.9.1 is the first version that supports Apple Silicon
      - name: Install Python 3.9.1
        run: |
          ./macos/install/python.sh -v 3.9.1
        shell: zsh {0}
      - name: Install Python 3.9.21
        run: |
          ./macos/install/python.sh -v 3.9.21
        shell: zsh {0}
      - name: Install Python 3.10.16
        run: |
          ./macos/install/python.sh -v 3.10.16
        shell: zsh {0}
      - name: Install Python 3.11.11
        run: |
          ./macos/install/python.sh -v 3.11.11
        shell: zsh {0}
      - name: Install Python 3.12.8
        run: |
          ./macos/install/python.sh -v 3.12.8
        shell: zsh {0}
      - name: Install Python 3.13.1
        run: |
          ./macos/install/python.sh -v 3.13.1
        shell: zsh {0}
      - name: List all Python versions
        run: |
          source ~/.zshrc
          pyenv versions
        shell: zsh {0}